### PR TITLE
Fix scrollbars.

### PR DESCRIPTION
**Pull request by matthooks**
before

after

### CODE REVIEW

**Comment by matthooks** [comment]
Ah, @wagenet beat me to it. Closing.

**Comment by wagenet** [comment]
@matthooks sorry about that! Would have been happy to merge yours.

**Comment by matthooks** [comment]
Hah, no worries ;)

**Comment by matthooks** [comment]
@wagenet Oh -- actually think your fix mighta broken the memory-scroll functionality...

**Comment by wagenet** [comment]
It did. I'm still working on it in a branch. Trying to get it to be document scroll since that better on mobile.

**Comment by matthooks** [comment]
Cool, lemme know if ya want help!

On Mar 29, 2016, at 8:55 PM, Peter Wagenet notifications@github.com wrote:

It did. I'm still working on it in a branch. Trying to get it to be document scroll since that better on mobile.

**Pull request closed without merging**
